### ISSUE TITLE
Parameter error in docs?

### ISSUE THREAD

**Issue by kevincoleman** [AlexMeah/check-nested#3]
I tried testing this function with basically the same sample provided in the readme, but it failed when using `checkNested(a, 'a.b.c.d');`. I removed the `a` from the start of the test string, and it returned properly. Not sure if I found a glitch or just broke the function to make it return as I expected, but in either case `checkNested(a, 'a.b.c.d');` didn’t return true.

**Comment by AlexMeah** [comment]
Sorry the README hasn't been updated in a while I don't really maintain this package anymore. I would recommend using https://www.npmjs.com/package/lodash.

I will add a note to the README

**Comment by kevincoleman** [comment]
No big! I just found it via the npm package. I almost just PR’d it, but yea. Thanks for the fix and the suggestion!

**Comment by AlexMeah** [comment]
That link was supposed to be https://www.npmjs.com/package/lodash.get :)

**Comment by kevincoleman** [comment]
Ahhh ok. :) Thanks!
